name: permission_service
description: Permission service utility - shows rationale dialogs before requesting native permissions
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
